# Generated by Django 3.2.6 on 2022-05-09 12:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Выберите цвет тега', image_field=None, max_length=50, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
